name: flutter_page_transition
description: A new Flutter Page Transition package.
version: 0.0.3
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:

