name: flutter_page_transition
description: A rich flutter page transition package.
version: 0.1.1
author: handoing <chenhandoing@gmail.com>
homepage: https://github.com/handoing/flutter_page_transition

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

