name: flutter_page_transition
description: A new Flutter Page Transition package.
version: 0.1.0
author: handoing
homepage: https://github.com/handoing/flutter_page_transition

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

